### PR TITLE
Gets AIS.py working with pyHanko as a replacement for itext.

### PR DESCRIPTION
**Pull request by Daverball**
Since itext has some licensing issues now and AIS.py is generally a bit outdated for current deployments. I've replaced itext with pyHanko as a python native replacement.

At the same time I dropped support for Python < 3.7, since pyHanko requires that version anyways, also Support for 3.6 is just about to run out, so there isn't much of a point to support anything below 3.7 anymore anyways.

pyHanko has a bit of a nicer API to prepare and fill the Signature in one go without having to create intermediary files, this however has the consequence that I've had to drop support for PDFs with an existing placeholder in the meantime. Technically it would be trivial to restore the old slower code path for prepared files and rely on PyPDF2 instead of PyHanko to compute the digest and place the signature contents. But for the sake of simplicity I've removed the feature. There seems to be no trivial way to handle both scenarios with pyHanko.

The API now also works on both stored files and stream handles, which makes it a bit more convenient to use in workflows where you might not actually have a stored PDF file. The output also no longer generates a temporary file, instead it generates a BytesIO buffer that can easily be written to a file. The example in the README was adjusted accordingly.

With pyHanko it will also be easy to improve the test suite, since pyHanko has built-in functions for validating PDF signatures. I have not bothered to do any of that yet however.

### CODE REVIEW

**Comment by lepistone** [comment]
First, thank you! I worked on this when I was at Camptocamp, and it's a pleasure to see a contribution.

The general idea of this PR sounds right to me:

Regarding itext, I remember that the choice was a pragmatic one, as we didn't manage to do what wee needed in pure Python at the time. I can imagine that vendoring itext brings licensing issues, and also forking a Java process is not ideal because it's slow and operations are more complicated. If today we can do without itext, sounds great to replace it.

Also running only on recent Pythons sounds like a no-brainer to me. Python 2 is finally gone, and with it the complexity of support both 2 and 3; also there is no much point supporting Python 3s that are not supported upstream.

A couple questions:
- Do you think that the test coverage is at least similar to before? I don't mean in a strict sense of lines of code, but more overall sense of confidence in the tests compared to before.
- This change would definitely need a major release, with an update in the History to explain the change from the point of view of the user: API changes, missing features, no more need for itext.

Specifically for my friends at Camptocamp: is the featured removed here - namely signing an existing placeholder - a problem for you?

**Comment by Daverball** [comment]
The test coverage should be roughly the same before. I dropped the tests for the feature I removed, but those didn't hit any additional code paths the other tests wouldn't have hit. If anything the test coverage is slightly better, since pyHanko will perform some additional validations that didn't happen before.

I am not even sure if AIS.py currently works, because the signatures we get back at the moment are larger than the buffer that was allocated by the old implementation. The old buffer was around 40KiB and the new signatures are around 50KiB. The old implementation did not check the buffer size so it resulted in an invalid PDF file at the end as the signature was written past the end of the buffer. pyHanko will raise an Exception if the Signature is too large to fit. The new implementation currently allocates 64KiB. But it might be a good idea to make this a setting that can be changed on the AIS instance, to support larger signatures in the future without internal changes to AIS.py.

I agree that there will need to be a major release with appropriate documentation within HISTORY. But I did not pull the trigger on that yet, since the current maintainers may wish to do that part themselves.

**Comment by freinhard** [comment]
Dear @lepistone. Any chance you can merge this PR and release a new version? Otherwise, we might have to think about a fork. But we would like to avoid this. I also contacted Camptocamp but haven't received any answer so far.

**Comment by lepistone** [comment]
> Dear @lepistone. Any chance you can merge this PR and release a new version? Otherwise, we might have to think about a fork. But we would like to avoid this. I also contacted Camptocamp but haven't received any answer so far.

I'm sorry I can't.

**Comment by freinhard** [comment]
FORK: https://github.com/seantis/AIS2.py

**Pull request closed without merging**
